CREATE TABLE order_summary (
  orderid int NOT NULL,
  action_taken varchar(255) DEFAULT NULL,
  billing_address varchar(255) DEFAULT NULL,
  customer_id int DEFAULT NULL,
  discounts double DEFAULT NULL,
  exception_date datetime(6) DEFAULT NULL,
  exception_description varchar(255) DEFAULT NULL,
  exception_type varchar(255) DEFAULT NULL,
  notes varchar(255) DEFAULT NULL,
  order_date datetime(6) DEFAULT NULL,
  order_status varchar(255) DEFAULT NULL,
  payment_method varchar(255) DEFAULT NULL,
  priority varchar(255) DEFAULT NULL,
  product_id int DEFAULT NULL,
  product_name varchar(255) DEFAULT NULL,
  quantity int DEFAULT NULL,
  resolution_notes varchar(255) DEFAULT NULL,
  resolution_status varchar(255) DEFAULT NULL,
  responsible_party varchar(255) DEFAULT NULL,
  shipping_address varchar(255) DEFAULT NULL,
  shipping_metho varchar(255) DEFAULT NULL,
  tax double DEFAULT NULL,
  total_amount double DEFAULT NULL,
  total_price double DEFAULT NULL,
  unit_price double DEFAULT NULL,
  PRIMARY KEY (orderid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

INSERT INTO order_summary (
    orderid, 
    customer_id, 
    order_date, 
    product_id, 
    product_name, 
    quantity, 
    unit_price, 
    total_price, 
    shipping_address, 
    billing_address, 
    payment_method, 
    order_status, 
    shipping_metho, 
    discounts, 
    tax, 
    total_amount, 
    notes, 
    exception_type, 
    exception_description, 
    exception_date, 
    resolution_status, 
    resolution_notes, 
    responsible_party, 
    priority, 
    action_taken
) VALUES (
    1, 
    1001, 
    NOW(), -- Use NOW() function to get current timestamp
    101, 
    'Product A', 
    2, 
    10.99, 
    21.98, 
    '123 Main St, City, Country', 
    '456 Secondary St, City, Country', 
    'Credit Card', 
    'reached controller', 
    'Standard Shipping', 
    0, 
    1.99, 
    23.97, 
    'Customer requested expedited delivery', 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    'Customer Service', 
    'Medium', 
    'Contact customer for confirmation'
);
